### ISSUE TITLE
Conflict with WooCommerce Memberships prevents the scheduling of User Membership expiration events

### ISSUE THREAD

**Issue by mudtar** [JJJ/post-type-switcher#6] opened 2017-03-22 19:39 UTC
The following takes place with the `twentyseventeen` theme enabled along with only the plugins `post-type-switcher`, `woocommerce`, and `woocommerce-memberships`.

After clicking "Save" when editing an existing `wc_user_membership` post via the WooCommerce Memberships backend, the HTTP request to `/wp-admin/post.php` times out, and a persistent PHP process continues running. This process creates thousands of `wc_user_membership` posts with a post_title of "wc_memberships_user_membership_expiry" and a post_status of "pending". The post_author of all these posts is the user who originally edited the `wc_user_membership`. Each of these new "wc_memberships_user_membership_expiry" posts references another "wc_memberships_user_membership_expiry" post in its post content. For example, if one of the newly-created "wc_memberships_user_membership_expiry" posts has an ID of 123456, the new "wc_memberships_user_membership_expiry" post with an ID of 123457 might have a post_content of `{"user_membership_id":123456}`.

Of course, many of these details are specific to `woocommerce-memberships`, but `post-type-switcher` is what introduces the issue. **After doing some testing, I discovered that the problem was introduced by 3063f42.**

Additionally, I noticed that versions 1.7.0 and 1.2.1 from the WordPress.org plugin repository, while not creating thousands of pending posts or hanging on post edit, still create two of these pending posts per `wc_user_membership` post update.

**Comment by mudtar** [comment] 2017-03-24 23:14
WooCommerce Memberships depends on [Action Scheduler](https://github.com/Prospress/action-scheduler) to handle its expiration events. I did some testing to see if Scheduled Actions were updating properly when Post Type Switcher was enabled, and I found that they were not. Even despite the timeouts, the "Edit User Membership" screen properly displays the newly-set "Expires" date, and it appears to stick. These changes don't make it to Scheduled Actions, however. This suggests that, for however long this conflict has existed, the WooCommerce Memberships expiry events have been corrupted to some extent. This means that all Scheduled Actions relating to User Memberships have to be updated or recreated based on existing User Membership data.

**Until this issue is fixed, I strongly urge you to include a warning on the WooCommerce.org Plugin Repo advising potential users of this plugin's incompatibility with WooCommerce Memberships.**

**Comment by krogsgard** [comment] 2019-04-29 14:36
@JJJ Is this something that can be addressed? Post Type Switcher is great, but it's a big risk on a site with WC Memberships enabled.

Would it be possible to exclude certain post types from being editable with Post Type Switcher, or some other action that could allow WC Memberships to remove it from the incompatible plugins list?

I am running both of these on a site and currently deactivate PTS unless I have to use it for an exact scenario.

Could you by chance take a look at the issue? Thanks.

**Comment by JJJ** [comment] 2019-04-29 16:35
If someone can send a copy of WooCommerce Memberships my way, that will go a long way towards helping identify what the correct fix is.

(The PTS plugin has encountered a number of conflicts over the years, and the majority of those were solved in the other plugin because they were doing something weird, resulting in me tweaking the code in PTS to avoid each specific edge-case.)

I’m happy to do it when I can reproduce it, or happy to have it done & accept a PR from someone else who can.

Sorry for the problems. People do weird-but-cool things with posts these days, and I totally support that, and think the PTS plugin should also.

**Comment by lkraav** [comment] 2019-04-29 17:53
@unfulvio can probably help.

**Comment by unfulvio** [comment] 2019-04-30 01:51
hey @JJJ contacted you in PostStatus, or you could drop your email at https://www.skyverge.com/contact/ so I can share a Memberships copy with you. Happy to chat about compatibility as well! Thanks!

**Comment by JJJ** [comment] 2019-04-30 05:57
I have WooCommerce, WooCommerce Memberships, bbPress, Sugar Calendar, and Post Type Switcher all active on my test installation. All of those plugins register several custom post types. 

## Classic Editor (Sugar Calendar):
<img width="311" alt="Screen Shot 2019-04-30 at 12 47 16 AM" src="https://user-images.githubusercontent.com/88951/56942675-8864bd00-6ae1-11e9-81fb-0c67941f4dff.png">

## Block Editor (Post):
<img width="291" alt="Screen Shot 2019-04-30 at 12 45 43 AM" src="https://user-images.githubusercontent.com/88951/56942649-68cd9480-6ae1-11e9-9bfc-ee5d81bc7b51.png">

## Classic Editor (Membership):
(See [this forum topic](https://wordpress.org/support/topic/dont-show-for-non-public-post-types/?replies=4#post-5849287) for why this post type appears)
<img width="309" alt="Screen Shot 2019-04-30 at 12 52 30 AM" src="https://user-images.githubusercontent.com/88951/56942818-425c2900-6ae2-11e9-98ae-7b810dbe16a4.png">

## Custom Editor (Member):
<img width="675" alt="Screen Shot 2019-04-30 at 12 56 25 AM" src="https://user-images.githubusercontent.com/88951/56942929-cb736000-6ae2-11e9-9c80-e59f89b58d36.png">

----

Clicking the "Update" or "Publish" buttons in any of these screens does _not appear_ to cause me any problems. Nothing hangs, and there are no extra entries in the `wp_posts` database table.

This is testing with the `master` branch. I'll keep trying to break this more tomorrow.

**Comment by unfulvio** [comment] 2019-04-30 06:01
IIRC, the problem arise with the Action Schedule library (shared with WooCommerce), where a lot of events were created in installations with the plugin and Memberships active. It could be that some of these duplicates were triggered by the events run by Action Scheduler. 

Could the plugin have a permanent / explicit exclusion for the following types:

* `wc_membership_plan`
* `wc_user_membership`
* `scheduled-action`

**Comment by JJJ** [comment] 2019-04-30 06:42
We’ve made it to 100k installs and several years or development without needing to permanently exclude any post types. I’d much, much rather that we fix the problem than mask the symptom.

**Comment by unfulvio** [comment] 2019-04-30 09:12
It doesn't look like the Memberships post types or the Action Scheduler post type comes listed in the types to switch to. So, maybe, those post type are effectively excluded, at least in UI.

Was the change prompted in https://wordpress.org/support/topic/dont-show-for-non-public-post-types/?replies=4#post-5849287 published before or after @mudtar initial issue report here?

From the v3.0.0 changelog I also see:

> Fix bug causing some post-types to switch unexpectedly


Could you elaborate a bit on what this changelog entry is referring to, please? I am wondering if, in fact, this fixed the issue we're talking about. I can't remember when 3.0.0 was added, and I can't see a date to compare it with some support tickets we had; but if I remember correctly the reported issues had this version running (although it may have been they updated, after issue was present in a former version that caused the problem).

Thank you

**Comment by JJJ** [comment] 2019-04-30 14:49
> Could you elaborate a bit on what this changelog entry is referring to

PTS was originally hooked to the `save_post` action, which meant that it was coming in after the original database write, to perform a second write specifically for the `post_type` value.

Since 2.0.0, it’s instead hooked to `wp_insert_post_data`, where it can manipulate the `post_type` value ahead of the original database write, eliminating the _need_ to check for recursive `save_post` calls.

The lesson I re’learned is that updating any post in the insert/update post function is super risky. Even if you `remove_all_filters()` or internally compare post IDs, it’s still possible for another plugin to get behind you and intentionally create 5 new different posts on every 1 `save_post` call, each with a different type or ID.

I had originally thought it was safest to change the post type at the very end (after everything else was done) but needed to switch to being very early (before anything was even saved) to avoid the myriad of recursion issues from everyone fighting over `save_post` priority.

That exact code change was 3063f42, 3 years ago, and most of these issues are newer than that.

There was a delay publishing 2.0.0 to WordPress.org, from a lack of feedback and confidence on my part that this was enough to fix this problem. (Perhaps that delay was enough to skew the timeline; hard to say.)

As for another way to theoretically dodge problems, I could hook in even earlier in the save callstack and “pin” the global post ID that’s being saved, compare the pinned ID to the currently filtered one, and not allow for multiple IDs to be pinned (except for bulk actions obviously.)

The only problem there is that I’m not sure if/when to “unpin” the ID. When is “done” actually “done done” enough to be safe?

Going to keep looking today and will report back.

**Comment by unfulvio** [comment] 2019-05-01 03:42
Thanks for the detailed story!

Based on the original issue description, and the timeline above, it all seems to fit the original issue reported. So I wonder if problems started before folks updated to 3.0.0. Maybe tests should be run with 2.x. If issue becomes obvious then, perhaps it may be safe to assume the bug is safely patched. I'm kinda busy this week, perhaps I can test this scenario next week.

Anyone replicating bugs/conflicts with 3.0.0?

**Comment by JJJ** [comment] 2019-07-01 05:33
Been keeping one eye on the forums, and haven't seen any new reports of this.

Motion to close, and reopen if new reports come in?

**Comment by unfulvio** [comment] 2019-07-02 01:35
I guess it's ok, sorry for lack of updates. 

If you plan to exclude attachments as mentioned in one of your earlier posts, I would still recommend excluding at least scheduled-action post types introduced by the Action Scheduled library shared by WooCommerce and many of its extensions. 

Or, **even better**, provide a filter for 3rd parties to add such exclusion (a filter would also allow actors to remove the exclusion again in the same manner, leaving a fair flexibility for all).

**Comment by oempire** [comment] 2019-08-13 02:24
Just so you know - we had this issue with previous versions of memberships and we dont use post type switcher. We worked with Skyverge and they implemented a fix which we haven't had a problem since.

When we saved a member (sometimes didnt happen all the time - it got stuck in a loop)

**Comment by JJJ** [comment] 2019-08-13 02:39
> they implemented a fix

Care to share? What versions of each plugin are you on?

**Comment by oempire** [comment] 2019-08-13 04:04
It was actually with MailChimp for WooCommerce Memberships plugin (same devs)

2019.01.15 - version 1.0.7
 * Fix - Avoid infinite loops during membership status transitions

**Comment by unfulvio** [comment] 2019-08-13 04:06
FYI given recent developments in both Memberships/Add ons and Post Type Switcher, we've removed the warning when Memberships detects PTS plugin in Memberships 1.14.0 released the other day. :crossed_fingers:

**Comment by ricks03** [comment] 2020-03-26 19:46
I still see the warning, running current WooCommerce Memberships, Post Type Switcher (3.2.0), and Wordpress.

"It looks like you have the following plugin installed which is not compatible with WooCommerce Memberships: Post Type Switcher. You may run into issues with Memberships while this is active. Please consult the documentation for more information."

**Comment by unfulvio** [comment] 2020-03-27 00:38
hey @ricks03 which version of Memberships are you running? we removed that warning a while ago, please try with a recent/latest version of Memberships, thanks

**Comment by ricks03** [comment] 2020-03-27 01:19
Version 1.13.1, which shows as the most recent in wordpress, although I see on your site at 1.17.1

**Comment by JJJ** [comment] 2021-03-13 04:44
Since it's been over 12 months, I think it's safe to close this issue here.

Definitely reopen if necessary. Thank you everyone for your help. I appreciate you. 👍

**Closed by JJJ** 2021-03-13 04:44 UTC
Labels: bug, help wanted
